"""replace sync outbox with deduplicated queue

Revision ID: 1a10179dd526
Revises: 7e56ac9f4545
Create Date: 2026-09-16 17:08:49.950639
"""

from collections.abc import Sequence
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

revision: str = '1a10179dd526'
down_revision: str | None = '7e56ac9f4545'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'attendance',
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    )
    op.create_table('sheet_sync_queue',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('desired_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'failed')", name='ck_sheet_sync_queue_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_sheet_sync_queue_attempts'),
    sa.CheckConstraint('desired_version >= 1', name='ck_sheet_sync_queue_version'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_index('ix_sheet_sync_queue_ready', 'sheet_sync_queue', ['status', 'next_retry_at'], unique=False)
    op.execute(
        sa.text(
            """
            INSERT INTO sheet_sync_queue (
                attendance_id,
                desired_version,
                status,
                attempts,
                next_retry_at,
                locked_at,
                last_error,
                updated_at
            )
            SELECT
                attendance_id,
                1,
                'pending',
                MAX(attempts),
                MIN(next_retry_at),
                NULL,
                MAX(last_error),
                MAX(created_at)
            FROM sheet_sync_outbox
            WHERE status IN ('pending', 'processing', 'failed')
            GROUP BY attendance_id
            """
        )
    )
    op.drop_index(op.f('ix_sheet_sync_outbox_ready'), table_name='sheet_sync_outbox')
    op.drop_table('sheet_sync_outbox')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet_sync_outbox',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_sheet_sync_outbox_status')),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sheet_sync_outbox_ready'), 'sheet_sync_outbox', ['status', 'next_retry_at'], unique=False)
    connection = op.get_bind()
    queue_rows = connection.execute(sa.text("SELECT * FROM sheet_sync_queue")).mappings()
    outbox_table = sa.table(
        "sheet_sync_outbox",
        sa.column("attendance_id", sa.Uuid()),
        sa.column("idempotency_key", sa.String()),
        sa.column("payload", sa.JSON()),
        sa.column("status", sa.String()),
        sa.column("attempts", sa.Integer()),
        sa.column("next_retry_at", sa.DateTime(timezone=True)),
        sa.column("locked_at", sa.DateTime(timezone=True)),
        sa.column("completed_at", sa.DateTime(timezone=True)),
        sa.column("last_error", sa.Text()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("id", sa.Uuid()),
    )
    for row in queue_rows:
        connection.execute(
            outbox_table.insert().values(
                attendance_id=row["attendance_id"],
                idempotency_key=f"sync:{row['attendance_id']}:v{row['desired_version']}",
                payload={},
                status="failed" if row["status"] == "failed" else "pending",
                attempts=row["attempts"],
                next_retry_at=row["next_retry_at"],
                locked_at=None,
                completed_at=None,
                last_error=row["last_error"],
                created_at=row["updated_at"],
                id=uuid4(),
            )
        )
    op.drop_index('ix_sheet_sync_queue_ready', table_name='sheet_sync_queue')
    op.drop_table('sheet_sync_queue')
    op.drop_column('attendance', 'version')
    # ### end Alembic commands ###
