"""initial schema

Revision ID: 3d1739749936
Revises: 
Create Date: 2026-09-16 16:48:17.904611
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3d1739749936'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_telegram_user_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lessons',
    sa.Column('lesson_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('subgroup', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("subgroup IN ('1', '2', 'общая')", name='ck_lessons_subgroup'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_date', 'sequence_number', name='uq_lessons_date_sequence')
    )
    op.create_index('ix_lessons_date_active', 'lessons', ['lesson_date', 'is_active'], unique=False)
    op.create_table('processed_updates',
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_table('sheet_mappings',
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('sheet_row', sa.Integer(), nullable=True),
    sa.Column('sheet_column', sa.Integer(), nullable=True),
    sa.Column('external_label', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('student', 'lesson')", name='ck_sheet_mappings_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_sheet_mappings_entity')
    )
    op.create_table('students',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('subgroup', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("subgroup IN ('1', '2')", name='ck_students_subgroup'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_students_active_name', 'students', ['is_active', 'full_name'], unique=False)
    op.create_table('admins',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('attendance',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('present', 'absent', 'bonus', 'excused')", name='ck_attendance_status'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_attendance_student_lesson')
    )
    op.create_index('ix_attendance_student_lesson', 'attendance', ['student_id', 'lesson_id'], unique=False)
    op.create_table('bonus_requests',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by_telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_bonus_requests_status'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_bonus_requests_student_lesson')
    )
    op.create_table('telegram_accounts',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'unlinked')", name='ck_telegram_accounts_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_telegram_accounts_active_student', 'telegram_accounts', ['student_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'approved')"), postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.create_index('uq_telegram_accounts_active_user', 'telegram_accounts', ['telegram_user_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'approved')"), postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.create_table('attendance_history',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('old_status', sa.String(length=16), nullable=True),
    sa.Column('new_status', sa.String(length=16), nullable=False),
    sa.Column('actor_telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_history_attendance_time', 'attendance_history', ['attendance_id', 'occurred_at'], unique=False)
    op.create_table('sheet_sync_outbox',
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_sheet_sync_outbox_status'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_sheet_sync_outbox_ready', 'sheet_sync_outbox', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sheet_sync_outbox_ready', table_name='sheet_sync_outbox')
    op.drop_table('sheet_sync_outbox')
    op.drop_index('ix_attendance_history_attendance_time', table_name='attendance_history')
    op.drop_table('attendance_history')
    op.drop_index('uq_telegram_accounts_active_user', table_name='telegram_accounts', sqlite_where=sa.text("status IN ('pending', 'approved')"), postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.drop_index('uq_telegram_accounts_active_student', table_name='telegram_accounts', sqlite_where=sa.text("status IN ('pending', 'approved')"), postgresql_where=sa.text("status IN ('pending', 'approved')"))
    op.drop_table('telegram_accounts')
    op.drop_table('bonus_requests')
    op.drop_index('ix_attendance_student_lesson', table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('admins')
    op.drop_index('ix_students_active_name', table_name='students')
    op.drop_table('students')
    op.drop_table('sheet_mappings')
    op.drop_table('processed_updates')
    op.drop_index('ix_lessons_date_active', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('app_settings')
    # ### end Alembic commands ###

