"""replace app settings with attendance settings

Revision ID: 7e56ac9f4545
Revises: b3344df95157
Create Date: 2026-09-16 17:03:31.419610
"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = '7e56ac9f4545'
down_revision: str | None = 'b3344df95157'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('attendance_window_hours', sa.Integer(), nullable=False),
    sa.Column('bonus_weekly_limit', sa.Integer(), nullable=False),
    sa.Column('allow_student_change', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_student_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('attendance_window_hours BETWEEN 1 AND 168', name='ck_attendance_settings_window'),
    sa.CheckConstraint('bonus_weekly_limit BETWEEN 0 AND 20', name='ck_attendance_settings_bonus_limit'),
    sa.CheckConstraint('id = 1', name='ck_attendance_settings_singleton'),
    sa.CheckConstraint('length(timezone) > 0', name='ck_attendance_settings_timezone'),
    sa.ForeignKeyConstraint(['updated_by_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    connection = op.get_bind()
    legacy_rows = {
        row.key: _decode_json_value(row.value)
        for row in connection.execute(sa.text("SELECT key, value FROM app_settings"))
    }
    settings_table = sa.table(
        "attendance_settings",
        sa.column("id", sa.Integer()),
        sa.column("timezone", sa.String()),
        sa.column("attendance_window_hours", sa.Integer()),
        sa.column("bonus_weekly_limit", sa.Integer()),
        sa.column("allow_student_change", sa.Boolean()),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        sa.column("updated_by_student_id", sa.Uuid()),
    )
    op.bulk_insert(
        settings_table,
        [
            {
                "id": 1,
                "timezone": str(
                    legacy_rows.get("timezone", legacy_rows.get("default_timezone", "Europe/Moscow"))
                ),
                "attendance_window_hours": int(legacy_rows.get("attendance_window_hours", 48)),
                "bonus_weekly_limit": int(legacy_rows.get("bonus_weekly_limit", 3)),
                "allow_student_change": _as_bool(legacy_rows.get("allow_student_change", False)),
                "updated_at": datetime.now(UTC),
                "updated_by_student_id": None,
            }
        ],
    )
    op.drop_table('app_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_by_telegram_user_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    connection = op.get_bind()
    row = connection.execute(sa.text("SELECT * FROM attendance_settings WHERE id = 1")).mappings().one()
    settings_table = sa.table(
        "app_settings",
        sa.column("key", sa.String()),
        sa.column("value", sa.JSON()),
        sa.column("updated_at", sa.DateTime(timezone=True)),
        sa.column("updated_by_telegram_user_id", sa.BigInteger()),
    )
    op.bulk_insert(
        settings_table,
        [
            {
                "key": key,
                "value": row[key],
                "updated_at": datetime.now(UTC),
                "updated_by_telegram_user_id": None,
            }
            for key in (
                "timezone",
                "attendance_window_hours",
                "bonus_weekly_limit",
                "allow_student_change",
            )
        ],
    )
    op.drop_table('attendance_settings')
    # ### end Alembic commands ###


def _decode_json_value(value: object) -> object:
    if not isinstance(value, str):
        return value
    import json

    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def _as_bool(value: object) -> bool:
    if isinstance(value, str):
        return value.lower() in {"1", "true", "yes", "on"}
    return bool(value)
