"""replace admins with student roles

Revision ID: b3344df95157
Revises: 3d1739749936
Create Date: 2026-09-16 17:00:12.519011
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b3344df95157'
down_revision: str | None = '3d1739749936'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_roles',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_student_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_student_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('starosta')", name='ck_student_roles_role'),
    sa.ForeignKeyConstraint(['assigned_by_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_student_roles_active', 'student_roles', ['student_id', 'role'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.execute(
        sa.text(
            """
            INSERT INTO student_roles (
                id,
                student_id,
                role,
                assigned_at,
                assigned_by_student_id,
                revoked_at,
                revoked_by_student_id
            )
            SELECT
                id,
                student_id,
                'starosta',
                created_at,
                NULL,
                NULL,
                NULL
            FROM admins
            WHERE student_id IS NOT NULL AND is_active
            """
        )
    )
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('telegram_user_id', sa.BIGINT(), nullable=False),
    sa.Column('student_id', sa.CHAR(length=32), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.execute(
        sa.text(
            """
            INSERT INTO admins (
                id,
                telegram_user_id,
                student_id,
                role,
                is_active,
                created_at
            )
            SELECT
                student_roles.id,
                telegram_accounts.telegram_user_id,
                student_roles.student_id,
                'starosta',
                TRUE,
                student_roles.assigned_at
            FROM student_roles
            JOIN telegram_accounts
              ON telegram_accounts.student_id = student_roles.student_id
             AND telegram_accounts.status = 'approved'
            WHERE student_roles.revoked_at IS NULL
            """
        )
    )
    op.drop_index('uq_student_roles_active', table_name='student_roles', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('student_roles')
    # ### end Alembic commands ###
