"""initial schema

Revision ID: ddb75d1bb7c0
Revises:
Create Date: 2026-09-17 13:07:33.258178
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "ddb75d1bb7c0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("lesson_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("subgroup", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("subgroup IN ('1', '2', 'общая')", name="ck_lessons_subgroup"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lesson_date", "sequence_number", name="uq_lessons_date_sequence"),
    )
    op.create_index("ix_lessons_date_active", "lessons", ["lesson_date", "is_active"], unique=False)
    op.create_table(
        "processed_updates",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("external_update_id", sa.String(length=128), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("provider IN ('telegram', 'vk')", name="ck_processed_updates_provider"),
        sa.PrimaryKeyConstraint("provider", "external_update_id"),
    )
    op.create_table(
        "sheet_mappings",
        sa.Column("entity_type", sa.String(length=16), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("sheet_name", sa.String(length=100), nullable=False),
        sa.Column("sheet_row", sa.Integer(), nullable=True),
        sa.Column("sheet_column", sa.Integer(), nullable=True),
        sa.Column("external_label", sa.String(length=255), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("entity_type IN ('student', 'lesson')", name="ck_sheet_mappings_entity_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_id", name="uq_sheet_mappings_entity"),
    )
    op.create_table(
        "students",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=False),
        sa.Column("subgroup", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("subgroup IN ('1', '2')", name="ck_students_subgroup"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_students_active_name", "students", ["is_active", "full_name"], unique=False)
    op.create_table(
        "attendance",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_provider", sa.String(length=16), nullable=False),
        sa.Column("created_by_external_user_id", sa.String(length=128), nullable=False),
        sa.Column("updated_by_provider", sa.String(length=16), nullable=False),
        sa.Column("updated_by_external_user_id", sa.String(length=128), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('present', 'absent', 'bonus', 'excused')", name="ck_attendance_status"
        ),
        sa.CheckConstraint("version >= 1", name="ck_attendance_version"),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "lesson_id", name="uq_attendance_student_lesson"),
    )
    op.create_index("ix_attendance_student_lesson", "attendance", ["student_id", "lesson_id"], unique=False)
    op.create_table(
        "attendance_requests",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("requested_status", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by_provider", sa.String(length=16), nullable=True),
        sa.Column("decided_by_external_user_id", sa.String(length=128), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')", name="ck_attendance_requests_status"
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "lesson_id", name="uq_attendance_requests_student_lesson"),
    )
    op.create_table(
        "external_accounts",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("external_user_id", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("provider IN ('telegram', 'vk')", name="ck_external_accounts_provider"),
        sa.CheckConstraint("status IN ('approved', 'unlinked')", name="ck_external_accounts_status"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_external_accounts_active_identity",
        "external_accounts",
        ["provider", "external_user_id"],
        unique=True,
        sqlite_where=sa.text("status = 'approved'"),
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.create_index(
        "uq_external_accounts_active_student_provider",
        "external_accounts",
        ["student_id", "provider"],
        unique=True,
        sqlite_where=sa.text("status = 'approved'"),
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.create_table(
        "student_roles",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by_student_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_student_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("role IN ('starosta', 'owner')", name="ck_student_roles_role"),
        sa.ForeignKeyConstraint(["assigned_by_student_id"], ["students.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["revoked_by_student_id"], ["students.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_student_roles_active",
        "student_roles",
        ["student_id", "role"],
        unique=True,
        sqlite_where=sa.text("revoked_at IS NULL"),
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "attendance_history",
        sa.Column("attendance_id", sa.Uuid(), nullable=False),
        sa.Column("old_status", sa.String(length=16), nullable=True),
        sa.Column("new_status", sa.String(length=16), nullable=False),
        sa.Column("actor_provider", sa.String(length=16), nullable=False),
        sa.Column("actor_external_user_id", sa.String(length=128), nullable=False),
        sa.Column("actor_role", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["attendance_id"], ["attendance.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attendance_history_attendance_time",
        "attendance_history",
        ["attendance_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "sheet_sync_queue",
        sa.Column("attendance_id", sa.Uuid(), nullable=False),
        sa.Column("desired_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'failed')", name="ck_sheet_sync_queue_status"
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_sheet_sync_queue_attempts"),
        sa.CheckConstraint("desired_version >= 1", name="ck_sheet_sync_queue_version"),
        sa.ForeignKeyConstraint(["attendance_id"], ["attendance.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("attendance_id"),
    )
    op.create_index(
        "ix_sheet_sync_queue_ready", "sheet_sync_queue", ["status", "next_retry_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sheet_sync_queue_ready", table_name="sheet_sync_queue")
    op.drop_table("sheet_sync_queue")
    op.drop_index("ix_attendance_history_attendance_time", table_name="attendance_history")
    op.drop_table("attendance_history")
    op.drop_index(
        "uq_student_roles_active",
        table_name="student_roles",
        sqlite_where=sa.text("revoked_at IS NULL"),
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("student_roles")
    op.drop_index(
        "uq_external_accounts_active_student_provider",
        table_name="external_accounts",
        sqlite_where=sa.text("status = 'approved'"),
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.drop_index(
        "uq_external_accounts_active_identity",
        table_name="external_accounts",
        sqlite_where=sa.text("status = 'approved'"),
        postgresql_where=sa.text("status = 'approved'"),
    )
    op.drop_table("external_accounts")
    op.drop_table("attendance_requests")
    op.drop_index("ix_attendance_student_lesson", table_name="attendance")
    op.drop_table("attendance")
    op.drop_index("ix_students_active_name", table_name="students")
    op.drop_table("students")
    op.drop_table("sheet_mappings")
    op.drop_table("processed_updates")
    op.drop_index("ix_lessons_date_active", table_name="lessons")
    op.drop_table("lessons")
    # ### end Alembic commands ###
